# Generated by Django 4.2.26 on 2025-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junkyard',
            fields=[
                ('junkyard_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
