# Generated by Django 4.2.26 on 2025-12-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='junkyard',
            name='zip_code',
            field=models.IntegerField(default=60433, max_length=5),
            preserve_default=False,
        ),
    ]
