# Generated by Django 4.2.26 on 2025-12-10 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0002_junkyard_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('junkyard_indentifier', models.CharField(max_length=30)),
                ('year', models.IntegerField(max_length=4)),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('row', models.IntegerField(verbose_name=5)),
                ('space', models.IntegerField(blank=True, verbose_name=5)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('junkyard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='yardsearcher.junkyard')),
            ],
        ),
    ]
