# Generated by Django 4.2.26 on 2025-12-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0003_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='row',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='space',
            field=models.IntegerField(blank=True, max_length=5),
        ),
    ]
