# Generated by Django 4.2.26 on 2025-12-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0004_alter_vehicle_row_alter_vehicle_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='space',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(),
        ),
    ]
