# Generated by Django 4.2.27 on 2025-12-17 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yardsearcher', '0005_alter_vehicle_row_alter_vehicle_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='junkyard',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='UserAllowedYard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junkyard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_yards', to='yardsearcher.junkyard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_yards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
