# Generated by Django 4.2.27 on 2025-12-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0006_junkyard_website_userallowedyard'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='available_date',
            field=models.DateField(default='8/25/2025'),
            preserve_default=False,
        ),
    ]
