# Generated by Django 4.2.27 on 2025-12-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0007_vehicle_available_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='junkyard_indentifier',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
