# Generated by Django 4.2.27 on 2025-12-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0008_alter_vehicle_junkyard_indentifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='junkyard_indentifier',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('junkyard', 'junkyard_indentifier'), name='unique_vehicle'),
        ),
    ]
