# Generated by Django 4.2.27 on 2025-12-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0009_alter_vehicle_junkyard_indentifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='junkyard_indentifier',
            new_name='junkyard_identifier',
        ),
    ]
