# Generated by Django 4.2.27 on 2025-12-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0010_rename_junkyard_indentifier_vehicle_junkyard_identifier'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='unique_vehicle',
        ),
        migrations.AlterField(
            model_name='junkyard',
            name='zip_code',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('junkyard', 'junkyard_identifier'), name='unique_vehicle'),
        ),
    ]
