# Generated by Django 4.2.27 on 2025-12-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0011_remove_vehicle_unique_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='junkyard',
            name='lat',
            field=models.IntegerField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='junkyard',
            name='long',
            field=models.IntegerField(default=0.0, editable=False),
        ),
    ]
