# Generated by Django 4.2.27 on 2025-12-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0012_junkyard_lat_junkyard_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junkyard',
            name='lat',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='junkyard',
            name='long',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
