# Generated by Django 4.2.27 on 2026-03-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0013_alter_junkyard_lat_alter_junkyard_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Successfully updated'), ('0', 'Failed')], max_length=1)),
                ('error', models.TextField(blank=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('junkyard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapes', to='yardsearcher.junkyard')),
            ],
        ),
    ]
