# Generated by Django 4.2.27 on 2026-03-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsearcher', '0014_scrape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='status',
            field=models.CharField(choices=[('1', 'SUCCESS'), ('0', 'FAILED')], editable=False, max_length=1),
        ),
    ]
